config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :healths, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  resources :contacts, only: [:new, :create]

  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
end

app/models/health.rb
class Health < ApplicationRecord
    validates :name, presence: true
    validates :height, presence: true
    validates :weight, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    PERMISSIBLE_ATTRIBUTES = %i(name)

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
            devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
        end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: "お問い合わせが完了しました！"
    else
      render 'new'
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_health, only: [:edit, :update, :destroy]

  def index
    @health = Health.all
  end

  def new
    @health = params[:back] ? Health.new(health_params) : Health.new
  end

  def create
    @health = Health.new(health_params)
    if @health.save
      # 一覧画面へ遷移して"入力設定が完了しました！"とメッセージを表示します。
      redirect_to healths_path, notice: "入力設定が完了しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def edit
  end

  def update
    if @health.update(health_params)
      redirect_to healths_path, notice: "入力データを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @health.destroy
    redirect_to healths_path, notice: "データを削除しました！"
  end

  def confirm
    @health = Health.new(health_params)
    render :new if @health.invalid?
  end

  private
    def health_params
      params.require(:health).permit(:name, :height, :weight, :content)
    end

    def set_health
      @health = Health.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_healths_path
        elsif action_name == 'edit'
            health_path
        end
    end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/contacts/new.html.erb
<h1>お問い合わせ</h1>

<%= form_for(@contact) do |f| %>

    <% if @contact.errors.any? %>
        <div id="error_explanation">
            <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <br>
    <%= f.submit %>
<% end %>

app/views/healths/_form.html.erb
<%= form_for(@health, url: choose_new_or_edit) do |f| %>
    <% if @health.errors.any? %>
        <div id="error_explanation">
            <h2><%= @health.errors.count %>件のエラーがあります。</h2>

            <ul>
                <% @health.errors.full_messages.each do | message | %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :height %>
    <%= f.text_field :height %>
    <br>
    <%= f.label :weight %>
    <%= f.text_field :weight %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <br>
    <%= f.submit %>
<% end %>

<%= link_to "入力一覧画面にもどる", healths_path %>

app/views/healths/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@health) do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :height %>
    <%= f.hidden_field :weight %>
    <%= f.hidden_field :content %>

    <p>名前: <%= @health.name %></p>
    <p>身長: <%= @health.height %></p>
    <p>体重: <%= @health.weight %></p>
    <p>メモ: <%= @health.content %></p>

    <%= f.submit "送信する" %>
<% end %>

<%= form_for(@health, url: new_health_path, method: 'get') do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :height %>
    <%= f.hidden_field :weight %>
    <%= f.hidden_field :content %>
    <%= f.submit "戻る", name: 'back'%>
<% end %>

app/views/healths/edit.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

app/views/healths/index.html.erb
<p><%= notice %></p>

<h1>入力一覧</h1>

<% @health.each do | health | %>
    <p>名前: <%= health.name %></p>
    <p>身長: <%= health.height.to_f %>cm</p>
    <p>体重: <%= health.weight.to_f %>kg</p>
    <p>メモ: <%= health.content %></p>
    <%= link_to '情報を編集する', edit_health_path(health.id) %>
    <%= link_to 'データを削除する', health_path(health.id), method: :delete, data:{confirm: '本当に削除していいですか？'} %>
    <br>
<% end %>

<br>
<%= link_to "情報を入力する", new_health_path %>

app/views/healths/new.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <ul>
            <li><%= link_to "Diet App", root_path %></li>
            <li><%= link_to "トップページ", root_path %></li>
            <li><%= link_to "身長・体重登録", healths_path %></li>
            <li><%= link_to "お問い合わせ", new_contact_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "マイページ", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "サインアップ", new_user_registration_path %></li>
            <% end %> 
        </ul>
      </header>

    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<section class="main-header">
    <p class="flash"><%= notice %><%= alert %></p>
    <img src="<%= asset_path "physical_measurement.jpg" %>">
</section>